### ISSUE TITLE
How to run on windows?

### ISSUE THREAD

**Issue by Abhi0725** [pklaus/brother_ql_web#34]
I am trying to run this on windows and getting error on font_helpers.py file method `get_fonts()`. Seems like fc-scan is working only on Linux?

**Comment by adityar-git** [comment]
I guess the method for this would be to read the Windows Fonts directory using the PowerShell command if the fs-scan is not supported. 

**__init__.py**
```
def main(app):
//Code here
if os.name.lower() == 'nt':
        print('Running in windows machine...')

        FONTS.scan_global_fonts_windows()
    else:
        print('Running in linux or other machine...')
        FONTS.scan_global_fonts()
        if app.config['FONT_FOLDER']:
            FONTS.scan_fonts_folder(app.config['FONT_FOLDER'])

//Code here
```

**fonts.py (Add these 2 methods)**
```
def scan_global_fonts_windows(self):
        try:
            raw = subprocess.run(['powershell.exe', 'Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"'], stdout=subprocess.PIPE)
        except:
            print("Error in parsing windows fonts")
            sys.exit(2)

        self.parse_win_fonts(raw)
```
```
def parse_win_fonts(self, raw):

        if raw.returncode != 0:
            return {'error': 'an error occurred while processing the fonts'}

        for line in raw.stdout.decode(sys.stdout.encoding).replace('\r\n', '\n').split('\n'):
            font = line.split(':')
            if len(font) < 2:
                continue
            
            font[0] = ''.join(ch for ch in font[0] if ch.isalnum() or ch == '(' or ch ==')')
            
            if '.ttf' in font[1] or '.otf' in font[1]:
                fontstyle_reg = re.search(r"\(([A-Za-z0-9_]+)\)", font[0])

                fontstyle = fontstyle_reg.group(1)
                fontname = font[0].replace(fontstyle, '').replace(')','').replace('(', '')
                fontpath = os.path.join(os.environ['WINDDIR'], 'fonts', font[1].strip())

                if ',' in fontname:
                    fontname = fontname.split()[0]
                fontname = fontname.strip()

                self.fonts[fontname][fontstyle] = fontpath
            else:
                pass
```

**routes.py**
Remove `from crypt import methods `(crypt is not supported in windows)

**Comment by FriedrichFroebel** [comment]
As documented inside the README, the `fontconfig` package is required for the package to work, so you will have to provide this package or at least the corresponding binary inside your `$PATH`. It seems like Anaconda (https://anaconda.org/anaconda/fontconfig) provides corresponding binaries, although I have not tested them.

**Comment by elhannaoui-ayoub** [comment]
@Abhi0725  did you find any solution to run this script on windows , i'm always getting this error
deprecation warning: brother_ql.devicedependent is deprecated and will be removed in a future release
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\brother_ql_web-master (1)\brother_ql_web-master\brother_ql_web.py", line 302, in <module>
    main()
  File "C:\Users\DELL\Downloads\brother_ql_web-master (1)\brother_ql_web-master\brother_ql_web.py", line 277, in main
    FONTS = get_fonts()
            ^^^^^^^^^^^
  File "C:\Users\DELL\Downloads\brother_ql_web-master (1)\brother_ql_web-master\font_helpers.py", line 29, in get_fonts
    styles = parts[2].split('=')[1].split(',')
             ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by FriedrichFroebel** [comment]
What is the plain output of the corresponding *fontconfig* subprocess command issued?
